"""remove-unique

Revision ID: 9ceabd845dc5
Revises: e031a1161899
Create Date: 2023-03-18 18:54:44.490394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ceabd845dc5'
down_revision = 'e031a1161899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pastel_art_guidance_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_height_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_neg_prompt_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_prompt_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_seed_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_steps_key', 'pastel_art', type_='unique')
    op.drop_constraint('pastel_art_width_key', 'pastel_art', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pastel_art_width_key', 'pastel_art', ['width'])
    op.create_unique_constraint('pastel_art_steps_key', 'pastel_art', ['steps'])
    op.create_unique_constraint('pastel_art_seed_key', 'pastel_art', ['seed'])
    op.create_unique_constraint('pastel_art_prompt_key', 'pastel_art', ['prompt'])
    op.create_unique_constraint('pastel_art_neg_prompt_key', 'pastel_art', ['neg_prompt'])
    op.create_unique_constraint('pastel_art_height_key', 'pastel_art', ['height'])
    op.create_unique_constraint('pastel_art_guidance_key', 'pastel_art', ['guidance'])
    # ### end Alembic commands ###
