"""update

Revision ID: e031a1161899
Revises: f4d72b9deb92
Create Date: 2023-03-18 18:47:10.462192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e031a1161899"
down_revision = "f4d72b9deb92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pastel_art", sa.Column("neg_prompt", sa.String(), nullable=False))
    op.add_column("pastel_art", sa.Column("seed", sa.Integer(), nullable=False))
    op.drop_constraint("pastel_art_negative_prompt_key", "pastel_art", type_="unique")
    op.create_unique_constraint(None, "pastel_art", ["neg_prompt"])
    op.create_unique_constraint(None, "pastel_art", ["seed"])
    op.drop_column("pastel_art", "negative_prompt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pastel_art",
        sa.Column("negative_prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "pastel_art", type_="unique")
    op.drop_constraint(None, "pastel_art", type_="unique")
    op.create_unique_constraint(
        "pastel_art_negative_prompt_key", "pastel_art", ["negative_prompt"]
    )
    op.drop_column("pastel_art", "seed")
    op.drop_column("pastel_art", "neg_prompt")
    # ### end Alembic commands ###
