"""init

Revision ID: f4d72b9deb92
Revises: 
Create Date: 2023-03-18 17:47:11.084627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4d72b9deb92"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pastel_art",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("negative_prompt", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("guidance", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint("guidance"),
        sa.UniqueConstraint("height"),
        sa.UniqueConstraint("image"),
        sa.UniqueConstraint("negative_prompt"),
        sa.UniqueConstraint("prompt"),
        sa.UniqueConstraint("steps"),
        sa.UniqueConstraint("width"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pastel_art")
    # ### end Alembic commands ###
